[project]
name = "databricks-cicd-devops"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pyspark~=3.5",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
